// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyoPN6EAy-KAJwCwOJJXDtDnfUoFjB4aE',
    appId: '1:149814264315:web:cb512c91267e46d3490b5e',
    messagingSenderId: '149814264315',
    projectId: 'edu-event-hub-7eb5b',
    authDomain: 'edu-event-hub-7eb5b.firebaseapp.com',
    storageBucket: 'edu-event-hub-7eb5b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASp9BHPi-fizfFb_SDKQByRx9oa04WduM',
    appId: '1:149814264315:android:683162aaf7055b19490b5e',
    messagingSenderId: '149814264315',
    projectId: 'edu-event-hub-7eb5b',
    storageBucket: 'edu-event-hub-7eb5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmDve2UynwHLGfXq5ynjffUnHnLObelJI',
    appId: '1:149814264315:ios:e980eee763de66ba490b5e',
    messagingSenderId: '149814264315',
    projectId: 'edu-event-hub-7eb5b',
    storageBucket: 'edu-event-hub-7eb5b.firebasestorage.app',
    iosBundleId: 'com.example.edueventHub',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyoPN6EAy-KAJwCwOJJXDtDnfUoFjB4aE',
    appId: '1:149814264315:web:ff9cf8990c685e7b490b5e',
    messagingSenderId: '149814264315',
    projectId: 'edu-event-hub-7eb5b',
    authDomain: 'edu-event-hub-7eb5b.firebaseapp.com',
    storageBucket: 'edu-event-hub-7eb5b.firebasestorage.app',
  );
}
